//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/KaniTactics/Game/KaniTacticsControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace KaniTactics.Game
{
    /// <summary>
    /// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/KaniTactics/Game/KaniTacticsControls.inputactions".
    /// </summary>
    /// <remarks>
    /// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
    /// </remarks>
    /// <example>
    /// <code>
    /// using namespace UnityEngine;
    /// using UnityEngine.InputSystem;
    ///
    /// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
    /// public class Example : MonoBehaviour, MyActions.IPlayerActions
    /// {
    ///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
    ///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
    ///
    ///     void Awake()
    ///     {
    ///         m_Actions = new MyActions_Actions();              // Create asset object.
    ///         m_Player = m_Actions.Player;                      // Extract action map object.
    ///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
    ///     }
    ///
    ///     void OnDestroy()
    ///     {
    ///         m_Actions.Dispose();                              // Destroy asset object.
    ///     }
    ///
    ///     void OnEnable()
    ///     {
    ///         m_Player.Enable();                                // Enable all actions within map.
    ///     }
    ///
    ///     void OnDisable()
    ///     {
    ///         m_Player.Disable();                               // Disable all actions within map.
    ///     }
    ///
    ///     #region Interface implementation of MyActions.IPlayerActions
    ///
    ///     // Invoked when "Move" action is either started, performed or canceled.
    ///     public void OnMove(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
    ///     }
    ///
    ///     // Invoked when "Attack" action is either started, performed or canceled.
    ///     public void OnAttack(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
    ///     }
    ///
    ///     #endregion
    /// }
    /// </code>
    /// </example>
    public partial class @KaniTacticsControls: IInputActionCollection2, IDisposable
    {
        /// <summary>
        /// Provides access to the underlying asset instance.
        /// </summary>
        public InputActionAsset asset { get; }

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @KaniTacticsControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""KaniTacticsControls"",
    ""maps"": [
        {
            ""name"": ""Select"",
            ""id"": ""94aaa3e1-18c5-4c81-a862-e63b47497c9d"",
            ""actions"": [
                {
                    ""name"": ""MoveLeft"",
                    ""type"": ""Button"",
                    ""id"": ""417cc8cd-87b4-4267-823f-f3bfaff6d114"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveRight"",
                    ""type"": ""Button"",
                    ""id"": ""4a84e0d0-affb-4125-805a-9083146296aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""5de40dc9-c01c-41ab-9ec1-6b1334ec9979"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Digit1"",
                    ""type"": ""Button"",
                    ""id"": ""68167085-edf2-4462-92a7-17295576687d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Digit2"",
                    ""type"": ""Button"",
                    ""id"": ""668e6c77-5ded-4815-89fc-c1c77875e52b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Digit3"",
                    ""type"": ""Button"",
                    ""id"": ""2bccdd0e-a949-4a9d-a144-4760765e0119"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Digit4"",
                    ""type"": ""Button"",
                    ""id"": ""57564c19-554e-412f-bfa0-60048ab5a834"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Digit5"",
                    ""type"": ""Button"",
                    ""id"": ""247246e2-b584-42be-b67c-9b6cea635372"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Digit6"",
                    ""type"": ""Button"",
                    ""id"": ""56ca97cf-ac78-4c6f-a1d7-87b661c565d6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Digit7"",
                    ""type"": ""Button"",
                    ""id"": ""b14f9775-60d9-4185-87d4-753bad6a323b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Digit8"",
                    ""type"": ""Button"",
                    ""id"": ""0d5bbc9c-69a9-4cd7-96ca-20d669a52e7e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Digit9"",
                    ""type"": ""Button"",
                    ""id"": ""143cb2ab-34ef-4f38-be10-5f8be9280dc6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cdd7cc0e-28ab-44c7-bbb7-c9546c4d2a85"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5c4d9b4-d125-4c75-85c4-4ecf307698a8"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd5c5781-217a-49fa-8fe9-0b1d29e420ee"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c05a8fd-e63a-459d-9721-725991bd5c5c"",
                    ""path"": ""<Keyboard>/numpadEnter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c73b9c67-e05d-49f2-988c-d2f53e9b3d9d"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Digit1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""491ebf0e-7998-4e2c-8128-b35c674fc055"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Digit2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5bb992a5-1b0d-45ab-914f-9e3fdbb83b2c"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Digit3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1985191-988d-41ca-b931-b7b782730f4c"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Digit4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9eb0a7d-9564-46aa-b618-037c386fe284"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Digit5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9285a306-6c88-4ae2-ac17-b6aa6e35645f"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Digit6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2cd39ed-0f4a-45a9-a411-c19fabde4ee7"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Digit7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44c19491-a068-48c2-859c-c2bb5276b601"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Digit8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3e67d707-edc7-4d0d-bddb-c35f4c1b50b2"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Digit9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MashP1"",
            ""id"": ""a2e3cdfd-546e-4998-82b3-fb229a22ac4b"",
            ""actions"": [
                {
                    ""name"": ""TapLeft"",
                    ""type"": ""Button"",
                    ""id"": ""42e459be-d07a-4a82-8751-13ab9ee80d7a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TapRight"",
                    ""type"": ""Button"",
                    ""id"": ""a30305ea-2c97-46c5-9571-49a140007130"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2adff3d0-fcad-4fee-9789-b6d13cee9cdd"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TapLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70ad497b-e3a3-4136-af53-9ff5bb594297"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TapRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MashP2"",
            ""id"": ""eb3d3415-09a6-40dd-90cc-94ab46f1d6df"",
            ""actions"": [
                {
                    ""name"": ""TapLeft"",
                    ""type"": ""Button"",
                    ""id"": ""d3ba16c3-6f73-485a-a82c-994201402ac0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TapRight"",
                    ""type"": ""Button"",
                    ""id"": ""ada679c1-1cd4-4893-85a6-3fc612fe588d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6ed6e12c-abf2-4573-b3ea-35897218d3c8"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TapLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7dc9e8be-853a-4c4e-ac70-6fafee401d55"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TapRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Pause"",
            ""id"": ""68f956e4-ed12-4fbc-88f8-255851373b0f"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""e772a102-2d20-48de-9153-23b030fd5ffa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""64f5110a-7aed-40d5-8b44-0e46d11d65b3"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""System"",
            ""id"": ""f1d3d205-36fb-49ba-880c-8e08eb67dfa6"",
            ""actions"": [
                {
                    ""name"": ""Restart"",
                    ""type"": ""Button"",
                    ""id"": ""0c03332d-4936-48a4-8d56-38826cf2ff57"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3c469be9-6830-4296-ba52-00f038f4802a"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Restart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Select
            m_Select = asset.FindActionMap("Select", throwIfNotFound: true);
            m_Select_MoveLeft = m_Select.FindAction("MoveLeft", throwIfNotFound: true);
            m_Select_MoveRight = m_Select.FindAction("MoveRight", throwIfNotFound: true);
            m_Select_Confirm = m_Select.FindAction("Confirm", throwIfNotFound: true);
            m_Select_Digit1 = m_Select.FindAction("Digit1", throwIfNotFound: true);
            m_Select_Digit2 = m_Select.FindAction("Digit2", throwIfNotFound: true);
            m_Select_Digit3 = m_Select.FindAction("Digit3", throwIfNotFound: true);
            m_Select_Digit4 = m_Select.FindAction("Digit4", throwIfNotFound: true);
            m_Select_Digit5 = m_Select.FindAction("Digit5", throwIfNotFound: true);
            m_Select_Digit6 = m_Select.FindAction("Digit6", throwIfNotFound: true);
            m_Select_Digit7 = m_Select.FindAction("Digit7", throwIfNotFound: true);
            m_Select_Digit8 = m_Select.FindAction("Digit8", throwIfNotFound: true);
            m_Select_Digit9 = m_Select.FindAction("Digit9", throwIfNotFound: true);
            // MashP1
            m_MashP1 = asset.FindActionMap("MashP1", throwIfNotFound: true);
            m_MashP1_TapLeft = m_MashP1.FindAction("TapLeft", throwIfNotFound: true);
            m_MashP1_TapRight = m_MashP1.FindAction("TapRight", throwIfNotFound: true);
            // MashP2
            m_MashP2 = asset.FindActionMap("MashP2", throwIfNotFound: true);
            m_MashP2_TapLeft = m_MashP2.FindAction("TapLeft", throwIfNotFound: true);
            m_MashP2_TapRight = m_MashP2.FindAction("TapRight", throwIfNotFound: true);
            // Pause
            m_Pause = asset.FindActionMap("Pause", throwIfNotFound: true);
            m_Pause_Pause = m_Pause.FindAction("Pause", throwIfNotFound: true);
            // System
            m_System = asset.FindActionMap("System", throwIfNotFound: true);
            m_System_Restart = m_System.FindAction("Restart", throwIfNotFound: true);
        }

        ~@KaniTacticsControls()
        {
            UnityEngine.Debug.Assert(!m_Select.enabled, "This will cause a leak and performance issues, KaniTacticsControls.Select.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_MashP1.enabled, "This will cause a leak and performance issues, KaniTacticsControls.MashP1.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_MashP2.enabled, "This will cause a leak and performance issues, KaniTacticsControls.MashP2.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_Pause.enabled, "This will cause a leak and performance issues, KaniTacticsControls.Pause.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_System.enabled, "This will cause a leak and performance issues, KaniTacticsControls.System.Disable() has not been called.");
        }

        /// <summary>
        /// Destroys this asset and all associated <see cref="InputAction"/> instances.
        /// </summary>
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
        public void Enable()
        {
            asset.Enable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
        public void Disable()
        {
            asset.Disable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
        public IEnumerable<InputBinding> bindings => asset.bindings;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Select
        private readonly InputActionMap m_Select;
        private List<ISelectActions> m_SelectActionsCallbackInterfaces = new List<ISelectActions>();
        private readonly InputAction m_Select_MoveLeft;
        private readonly InputAction m_Select_MoveRight;
        private readonly InputAction m_Select_Confirm;
        private readonly InputAction m_Select_Digit1;
        private readonly InputAction m_Select_Digit2;
        private readonly InputAction m_Select_Digit3;
        private readonly InputAction m_Select_Digit4;
        private readonly InputAction m_Select_Digit5;
        private readonly InputAction m_Select_Digit6;
        private readonly InputAction m_Select_Digit7;
        private readonly InputAction m_Select_Digit8;
        private readonly InputAction m_Select_Digit9;
        /// <summary>
        /// Provides access to input actions defined in input action map "Select".
        /// </summary>
        public struct SelectActions
        {
            private @KaniTacticsControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public SelectActions(@KaniTacticsControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Select/MoveLeft".
            /// </summary>
            public InputAction @MoveLeft => m_Wrapper.m_Select_MoveLeft;
            /// <summary>
            /// Provides access to the underlying input action "Select/MoveRight".
            /// </summary>
            public InputAction @MoveRight => m_Wrapper.m_Select_MoveRight;
            /// <summary>
            /// Provides access to the underlying input action "Select/Confirm".
            /// </summary>
            public InputAction @Confirm => m_Wrapper.m_Select_Confirm;
            /// <summary>
            /// Provides access to the underlying input action "Select/Digit1".
            /// </summary>
            public InputAction @Digit1 => m_Wrapper.m_Select_Digit1;
            /// <summary>
            /// Provides access to the underlying input action "Select/Digit2".
            /// </summary>
            public InputAction @Digit2 => m_Wrapper.m_Select_Digit2;
            /// <summary>
            /// Provides access to the underlying input action "Select/Digit3".
            /// </summary>
            public InputAction @Digit3 => m_Wrapper.m_Select_Digit3;
            /// <summary>
            /// Provides access to the underlying input action "Select/Digit4".
            /// </summary>
            public InputAction @Digit4 => m_Wrapper.m_Select_Digit4;
            /// <summary>
            /// Provides access to the underlying input action "Select/Digit5".
            /// </summary>
            public InputAction @Digit5 => m_Wrapper.m_Select_Digit5;
            /// <summary>
            /// Provides access to the underlying input action "Select/Digit6".
            /// </summary>
            public InputAction @Digit6 => m_Wrapper.m_Select_Digit6;
            /// <summary>
            /// Provides access to the underlying input action "Select/Digit7".
            /// </summary>
            public InputAction @Digit7 => m_Wrapper.m_Select_Digit7;
            /// <summary>
            /// Provides access to the underlying input action "Select/Digit8".
            /// </summary>
            public InputAction @Digit8 => m_Wrapper.m_Select_Digit8;
            /// <summary>
            /// Provides access to the underlying input action "Select/Digit9".
            /// </summary>
            public InputAction @Digit9 => m_Wrapper.m_Select_Digit9;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Select; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="SelectActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(SelectActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="SelectActions" />
            public void AddCallbacks(ISelectActions instance)
            {
                if (instance == null || m_Wrapper.m_SelectActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_SelectActionsCallbackInterfaces.Add(instance);
                @MoveLeft.started += instance.OnMoveLeft;
                @MoveLeft.performed += instance.OnMoveLeft;
                @MoveLeft.canceled += instance.OnMoveLeft;
                @MoveRight.started += instance.OnMoveRight;
                @MoveRight.performed += instance.OnMoveRight;
                @MoveRight.canceled += instance.OnMoveRight;
                @Confirm.started += instance.OnConfirm;
                @Confirm.performed += instance.OnConfirm;
                @Confirm.canceled += instance.OnConfirm;
                @Digit1.started += instance.OnDigit1;
                @Digit1.performed += instance.OnDigit1;
                @Digit1.canceled += instance.OnDigit1;
                @Digit2.started += instance.OnDigit2;
                @Digit2.performed += instance.OnDigit2;
                @Digit2.canceled += instance.OnDigit2;
                @Digit3.started += instance.OnDigit3;
                @Digit3.performed += instance.OnDigit3;
                @Digit3.canceled += instance.OnDigit3;
                @Digit4.started += instance.OnDigit4;
                @Digit4.performed += instance.OnDigit4;
                @Digit4.canceled += instance.OnDigit4;
                @Digit5.started += instance.OnDigit5;
                @Digit5.performed += instance.OnDigit5;
                @Digit5.canceled += instance.OnDigit5;
                @Digit6.started += instance.OnDigit6;
                @Digit6.performed += instance.OnDigit6;
                @Digit6.canceled += instance.OnDigit6;
                @Digit7.started += instance.OnDigit7;
                @Digit7.performed += instance.OnDigit7;
                @Digit7.canceled += instance.OnDigit7;
                @Digit8.started += instance.OnDigit8;
                @Digit8.performed += instance.OnDigit8;
                @Digit8.canceled += instance.OnDigit8;
                @Digit9.started += instance.OnDigit9;
                @Digit9.performed += instance.OnDigit9;
                @Digit9.canceled += instance.OnDigit9;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="SelectActions" />
            private void UnregisterCallbacks(ISelectActions instance)
            {
                @MoveLeft.started -= instance.OnMoveLeft;
                @MoveLeft.performed -= instance.OnMoveLeft;
                @MoveLeft.canceled -= instance.OnMoveLeft;
                @MoveRight.started -= instance.OnMoveRight;
                @MoveRight.performed -= instance.OnMoveRight;
                @MoveRight.canceled -= instance.OnMoveRight;
                @Confirm.started -= instance.OnConfirm;
                @Confirm.performed -= instance.OnConfirm;
                @Confirm.canceled -= instance.OnConfirm;
                @Digit1.started -= instance.OnDigit1;
                @Digit1.performed -= instance.OnDigit1;
                @Digit1.canceled -= instance.OnDigit1;
                @Digit2.started -= instance.OnDigit2;
                @Digit2.performed -= instance.OnDigit2;
                @Digit2.canceled -= instance.OnDigit2;
                @Digit3.started -= instance.OnDigit3;
                @Digit3.performed -= instance.OnDigit3;
                @Digit3.canceled -= instance.OnDigit3;
                @Digit4.started -= instance.OnDigit4;
                @Digit4.performed -= instance.OnDigit4;
                @Digit4.canceled -= instance.OnDigit4;
                @Digit5.started -= instance.OnDigit5;
                @Digit5.performed -= instance.OnDigit5;
                @Digit5.canceled -= instance.OnDigit5;
                @Digit6.started -= instance.OnDigit6;
                @Digit6.performed -= instance.OnDigit6;
                @Digit6.canceled -= instance.OnDigit6;
                @Digit7.started -= instance.OnDigit7;
                @Digit7.performed -= instance.OnDigit7;
                @Digit7.canceled -= instance.OnDigit7;
                @Digit8.started -= instance.OnDigit8;
                @Digit8.performed -= instance.OnDigit8;
                @Digit8.canceled -= instance.OnDigit8;
                @Digit9.started -= instance.OnDigit9;
                @Digit9.performed -= instance.OnDigit9;
                @Digit9.canceled -= instance.OnDigit9;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="SelectActions.UnregisterCallbacks(ISelectActions)" />.
            /// </summary>
            /// <seealso cref="SelectActions.UnregisterCallbacks(ISelectActions)" />
            public void RemoveCallbacks(ISelectActions instance)
            {
                if (m_Wrapper.m_SelectActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="SelectActions.AddCallbacks(ISelectActions)" />
            /// <seealso cref="SelectActions.RemoveCallbacks(ISelectActions)" />
            /// <seealso cref="SelectActions.UnregisterCallbacks(ISelectActions)" />
            public void SetCallbacks(ISelectActions instance)
            {
                foreach (var item in m_Wrapper.m_SelectActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_SelectActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="SelectActions" /> instance referencing this action map.
        /// </summary>
        public SelectActions @Select => new SelectActions(this);

        // MashP1
        private readonly InputActionMap m_MashP1;
        private List<IMashP1Actions> m_MashP1ActionsCallbackInterfaces = new List<IMashP1Actions>();
        private readonly InputAction m_MashP1_TapLeft;
        private readonly InputAction m_MashP1_TapRight;
        /// <summary>
        /// Provides access to input actions defined in input action map "MashP1".
        /// </summary>
        public struct MashP1Actions
        {
            private @KaniTacticsControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public MashP1Actions(@KaniTacticsControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "MashP1/TapLeft".
            /// </summary>
            public InputAction @TapLeft => m_Wrapper.m_MashP1_TapLeft;
            /// <summary>
            /// Provides access to the underlying input action "MashP1/TapRight".
            /// </summary>
            public InputAction @TapRight => m_Wrapper.m_MashP1_TapRight;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_MashP1; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="MashP1Actions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(MashP1Actions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="MashP1Actions" />
            public void AddCallbacks(IMashP1Actions instance)
            {
                if (instance == null || m_Wrapper.m_MashP1ActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_MashP1ActionsCallbackInterfaces.Add(instance);
                @TapLeft.started += instance.OnTapLeft;
                @TapLeft.performed += instance.OnTapLeft;
                @TapLeft.canceled += instance.OnTapLeft;
                @TapRight.started += instance.OnTapRight;
                @TapRight.performed += instance.OnTapRight;
                @TapRight.canceled += instance.OnTapRight;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="MashP1Actions" />
            private void UnregisterCallbacks(IMashP1Actions instance)
            {
                @TapLeft.started -= instance.OnTapLeft;
                @TapLeft.performed -= instance.OnTapLeft;
                @TapLeft.canceled -= instance.OnTapLeft;
                @TapRight.started -= instance.OnTapRight;
                @TapRight.performed -= instance.OnTapRight;
                @TapRight.canceled -= instance.OnTapRight;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="MashP1Actions.UnregisterCallbacks(IMashP1Actions)" />.
            /// </summary>
            /// <seealso cref="MashP1Actions.UnregisterCallbacks(IMashP1Actions)" />
            public void RemoveCallbacks(IMashP1Actions instance)
            {
                if (m_Wrapper.m_MashP1ActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="MashP1Actions.AddCallbacks(IMashP1Actions)" />
            /// <seealso cref="MashP1Actions.RemoveCallbacks(IMashP1Actions)" />
            /// <seealso cref="MashP1Actions.UnregisterCallbacks(IMashP1Actions)" />
            public void SetCallbacks(IMashP1Actions instance)
            {
                foreach (var item in m_Wrapper.m_MashP1ActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_MashP1ActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="MashP1Actions" /> instance referencing this action map.
        /// </summary>
        public MashP1Actions @MashP1 => new MashP1Actions(this);

        // MashP2
        private readonly InputActionMap m_MashP2;
        private List<IMashP2Actions> m_MashP2ActionsCallbackInterfaces = new List<IMashP2Actions>();
        private readonly InputAction m_MashP2_TapLeft;
        private readonly InputAction m_MashP2_TapRight;
        /// <summary>
        /// Provides access to input actions defined in input action map "MashP2".
        /// </summary>
        public struct MashP2Actions
        {
            private @KaniTacticsControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public MashP2Actions(@KaniTacticsControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "MashP2/TapLeft".
            /// </summary>
            public InputAction @TapLeft => m_Wrapper.m_MashP2_TapLeft;
            /// <summary>
            /// Provides access to the underlying input action "MashP2/TapRight".
            /// </summary>
            public InputAction @TapRight => m_Wrapper.m_MashP2_TapRight;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_MashP2; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="MashP2Actions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(MashP2Actions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="MashP2Actions" />
            public void AddCallbacks(IMashP2Actions instance)
            {
                if (instance == null || m_Wrapper.m_MashP2ActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_MashP2ActionsCallbackInterfaces.Add(instance);
                @TapLeft.started += instance.OnTapLeft;
                @TapLeft.performed += instance.OnTapLeft;
                @TapLeft.canceled += instance.OnTapLeft;
                @TapRight.started += instance.OnTapRight;
                @TapRight.performed += instance.OnTapRight;
                @TapRight.canceled += instance.OnTapRight;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="MashP2Actions" />
            private void UnregisterCallbacks(IMashP2Actions instance)
            {
                @TapLeft.started -= instance.OnTapLeft;
                @TapLeft.performed -= instance.OnTapLeft;
                @TapLeft.canceled -= instance.OnTapLeft;
                @TapRight.started -= instance.OnTapRight;
                @TapRight.performed -= instance.OnTapRight;
                @TapRight.canceled -= instance.OnTapRight;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="MashP2Actions.UnregisterCallbacks(IMashP2Actions)" />.
            /// </summary>
            /// <seealso cref="MashP2Actions.UnregisterCallbacks(IMashP2Actions)" />
            public void RemoveCallbacks(IMashP2Actions instance)
            {
                if (m_Wrapper.m_MashP2ActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="MashP2Actions.AddCallbacks(IMashP2Actions)" />
            /// <seealso cref="MashP2Actions.RemoveCallbacks(IMashP2Actions)" />
            /// <seealso cref="MashP2Actions.UnregisterCallbacks(IMashP2Actions)" />
            public void SetCallbacks(IMashP2Actions instance)
            {
                foreach (var item in m_Wrapper.m_MashP2ActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_MashP2ActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="MashP2Actions" /> instance referencing this action map.
        /// </summary>
        public MashP2Actions @MashP2 => new MashP2Actions(this);

        // Pause
        private readonly InputActionMap m_Pause;
        private List<IPauseActions> m_PauseActionsCallbackInterfaces = new List<IPauseActions>();
        private readonly InputAction m_Pause_Pause;
        /// <summary>
        /// Provides access to input actions defined in input action map "Pause".
        /// </summary>
        public struct PauseActions
        {
            private @KaniTacticsControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public PauseActions(@KaniTacticsControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Pause/Pause".
            /// </summary>
            public InputAction @Pause => m_Wrapper.m_Pause_Pause;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Pause; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="PauseActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(PauseActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="PauseActions" />
            public void AddCallbacks(IPauseActions instance)
            {
                if (instance == null || m_Wrapper.m_PauseActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_PauseActionsCallbackInterfaces.Add(instance);
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="PauseActions" />
            private void UnregisterCallbacks(IPauseActions instance)
            {
                @Pause.started -= instance.OnPause;
                @Pause.performed -= instance.OnPause;
                @Pause.canceled -= instance.OnPause;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PauseActions.UnregisterCallbacks(IPauseActions)" />.
            /// </summary>
            /// <seealso cref="PauseActions.UnregisterCallbacks(IPauseActions)" />
            public void RemoveCallbacks(IPauseActions instance)
            {
                if (m_Wrapper.m_PauseActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="PauseActions.AddCallbacks(IPauseActions)" />
            /// <seealso cref="PauseActions.RemoveCallbacks(IPauseActions)" />
            /// <seealso cref="PauseActions.UnregisterCallbacks(IPauseActions)" />
            public void SetCallbacks(IPauseActions instance)
            {
                foreach (var item in m_Wrapper.m_PauseActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_PauseActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="PauseActions" /> instance referencing this action map.
        /// </summary>
        public PauseActions @Pause => new PauseActions(this);

        // System
        private readonly InputActionMap m_System;
        private List<ISystemActions> m_SystemActionsCallbackInterfaces = new List<ISystemActions>();
        private readonly InputAction m_System_Restart;
        /// <summary>
        /// Provides access to input actions defined in input action map "System".
        /// </summary>
        public struct SystemActions
        {
            private @KaniTacticsControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public SystemActions(@KaniTacticsControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "System/Restart".
            /// </summary>
            public InputAction @Restart => m_Wrapper.m_System_Restart;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_System; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="SystemActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(SystemActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="SystemActions" />
            public void AddCallbacks(ISystemActions instance)
            {
                if (instance == null || m_Wrapper.m_SystemActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_SystemActionsCallbackInterfaces.Add(instance);
                @Restart.started += instance.OnRestart;
                @Restart.performed += instance.OnRestart;
                @Restart.canceled += instance.OnRestart;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="SystemActions" />
            private void UnregisterCallbacks(ISystemActions instance)
            {
                @Restart.started -= instance.OnRestart;
                @Restart.performed -= instance.OnRestart;
                @Restart.canceled -= instance.OnRestart;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="SystemActions.UnregisterCallbacks(ISystemActions)" />.
            /// </summary>
            /// <seealso cref="SystemActions.UnregisterCallbacks(ISystemActions)" />
            public void RemoveCallbacks(ISystemActions instance)
            {
                if (m_Wrapper.m_SystemActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="SystemActions.AddCallbacks(ISystemActions)" />
            /// <seealso cref="SystemActions.RemoveCallbacks(ISystemActions)" />
            /// <seealso cref="SystemActions.UnregisterCallbacks(ISystemActions)" />
            public void SetCallbacks(ISystemActions instance)
            {
                foreach (var item in m_Wrapper.m_SystemActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_SystemActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="SystemActions" /> instance referencing this action map.
        /// </summary>
        public SystemActions @System => new SystemActions(this);
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Select" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="SelectActions.AddCallbacks(ISelectActions)" />
        /// <seealso cref="SelectActions.RemoveCallbacks(ISelectActions)" />
        public interface ISelectActions
        {
            /// <summary>
            /// Method invoked when associated input action "MoveLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnMoveLeft(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "MoveRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnMoveRight(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Confirm" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnConfirm(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Digit1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnDigit1(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Digit2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnDigit2(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Digit3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnDigit3(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Digit4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnDigit4(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Digit5" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnDigit5(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Digit6" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnDigit6(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Digit7" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnDigit7(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Digit8" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnDigit8(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Digit9" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnDigit9(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "MashP1" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="MashP1Actions.AddCallbacks(IMashP1Actions)" />
        /// <seealso cref="MashP1Actions.RemoveCallbacks(IMashP1Actions)" />
        public interface IMashP1Actions
        {
            /// <summary>
            /// Method invoked when associated input action "TapLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnTapLeft(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "TapRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnTapRight(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "MashP2" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="MashP2Actions.AddCallbacks(IMashP2Actions)" />
        /// <seealso cref="MashP2Actions.RemoveCallbacks(IMashP2Actions)" />
        public interface IMashP2Actions
        {
            /// <summary>
            /// Method invoked when associated input action "TapLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnTapLeft(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "TapRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnTapRight(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Pause" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="PauseActions.AddCallbacks(IPauseActions)" />
        /// <seealso cref="PauseActions.RemoveCallbacks(IPauseActions)" />
        public interface IPauseActions
        {
            /// <summary>
            /// Method invoked when associated input action "Pause" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnPause(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "System" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="SystemActions.AddCallbacks(ISystemActions)" />
        /// <seealso cref="SystemActions.RemoveCallbacks(ISystemActions)" />
        public interface ISystemActions
        {
            /// <summary>
            /// Method invoked when associated input action "Restart" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnRestart(InputAction.CallbackContext context);
        }
    }
}
